hotwax/facilities

src/store/modules/facility/actions.ts

When passing `defaultDaysToShip` in the fieldList of performFind as the first value, count in the result is not correct.
Closes #
Moved the parameter `defaultDaysToShip` as the last value in fieldList

Fixed: issue of performFind count not correct when passing defaultDaysToShip

---

src/locales/en.json
src/services/FacilityService.ts
src/store/modules/facility/actions.ts
src/views/FacilityDetails.vue

Closes #16
-  [x] I read and followed [contribution rules](https://github.com/hotwax/facilities#contribution-guideline)

Implemented: support to update the fulfillment settings from details page(#16)

---

src/views/CreateFacility.vue
src/views/FacilityDetails.vue
src/views/FindFacilities.vue

Improved: facility creation by creating default location and updating sell online setting on find page   

---

src/components/FacilityAddressModal.vue
src/views/AddFacilityAddress.vue

Closes #48 
Fixed: Disabled state when no country is selected (#48).

Fixed: Disabled state when no country is selected (#48).

---

src/locales/en.json
src/views/Parking.vue

Closes #87
Improved code to show 'Not scheduled' instead of '-' if not brokering job is scheduled.

Improved: code to show 'Not scheduled' when no brokering job is scheduled (#87)

---

src/locales/en.json
src/views/AddFacilityConfig.vue
src/views/FacilityDetails.vue

Improved: UI to display a block level add button on the product store card when no stores are linked to the facility(#96)

---

src/components/FacilityMappingPopover.vue
src/views/FacilityDetails.vue

Closes #114 
Removed: logic to always show faciility external id card
Added harcoded option in popover to add external id
Before:
Card is always displayed on UI irrespective of whether externalId on facility is present or not
After:

Improved: UI to add externalId for facility(#114)

---

src/locales/en.json
src/views/AddFacilityConfig.vue

Closes #
Implemented: support to set reset password email while creating facility (#115).

Implemented: support to set reset password email while creating facility (#115).

---

src/components/FacilityGroupActionsPopover.vue
src/services/FacilityService.ts

Closes #142 
Fixed: delete facility group functionality (#142).

Fixed: delete facility group functionality (#142).

---

src/views/FindGroups.vue

Closes #140
Improved code to show all the groups in the select dropdown of facility group type selector in find groups page.
- Groups associated with other group types are disabled by default in the select options.

Improved: code to show all groups in the group type dropdown (#140)

---

src/locales/en.json
src/store/modules/facility/FacilityState.ts
src/store/modules/facility/actions.ts
src/store/modules/facility/index.ts
src/views/FindFacilities.vue
src/views/FindGroups.vue

Closes #
Improved: facility group UI to redirect the user to find facilities page with the group filter applied when clicking on facilities item (#141).

Improved: facility group UI to redirect the user to find facilities page with the group filter applied when clicking on facilities item (#141).

---

src/locales/en.json
src/views/FindGroups.vue

Closes #158 
Added "groups" label after the number in group type mapping where there is more than one type selected. 
<
!-- If you made any changes in the UI layer, please provide before/after screenshots -->

Improved: added 'groups' label and its translation in group type mapping

---

src/store/modules/facility/actions.ts

Closes #169
Fixed issue of inventory channel groups not showing until page refersh in facility details page.

Fixed: inventory channel groups not showing until page refresh (#169)

---

src/views/FindFacilities.vue

Closes #173
Removed the text overlapping issue which is enhancing readability in facility details page by moving the text in next line when screen size is getting small.
description and Why It's Useful
It is necessary because when user will open the facility page in small screen size , the text was overlapping with "sell online" button. So, It enhances the user experience.

Improved: Text overlapping in facility view page(#173)

---

src/views/CreateFacility.vue

Closes #196
Improved code to dynamically display server message in the toast message in case create facility api fails due to duplicate facility id.

Improved: toast message to show server message in case of failure in create facility(#196)

---

src/store/modules/facility/actions.ts

Closes #202
All was not showing up by default in find facilites because of missing entry in clearQueryState. Hence added the missing key for facilityGroupId filter to fix it.

fixed: all not showing up by default in find facilities filters (#202)

---

src/components/FacilityAddressModal.vue
src/views/AddFacilityAddress.vue
src/views/FacilityDetails.vue

Closes #199
Fixed: 
- Loader not dismissing on mobile change 2nd or more times
- Truncation in identification value in facility mappings card.
- Added "-" as a seperator between country code and mobile number.

Fixed: loader not dismissing on telecom update and truncation in facility mappings card (#199)

---

.env.example
src/components/FacilityLoginActionPopover.vue

Related Issue: https://github.com/hotwax/user-management/issues/107
Redirecting to users login route with oms, token and partyId such that current session is used in users app when redirecting from facilities to users.

Improved: logic to redirect to login page with users partyId and login credentials for opening current session in users app (user-107)

---

src/views/FindFacilities.vue
src/views/FindGroups.vue
src/views/Parking.vue
src/views/Settings.vue

Closes #215
Removed the ion-back-button from the pages which opens up using tab navigation.
Before 
After

Improved: removed the back button from the tab pages (#215)

---

src/components/AddFacilityToGroupModal.vue

Related Issue #220
Fixed all facilities not showing in the select facilities modal in the facility group card.
- Earlier we were fetching the facilities with "FacilityView" entity which don't fetch facilities which have thruDate of group association in it.
- Instead now we are using "Facility" entity to fetch all the facility regardless of their linking with group.

Fixed: all facilities not showing up in select facilities modal in facility group card. (#220)

---

src/components/TimezoneModal.vue
src/locales/en.json

Closes #
Added ion-spinner inside the Timezone modal to enhance UI

Implemented: Spinner in timezone modal so users can see that data is being fetched

---

src/components/FacilityAddressModal.vue
src/locales/en.json
src/store/modules/facility/actions.ts
src/views/AddFacilityAddress.vue
src/views/CreateFacility.vue
src/views/FacilityDetails.vue

Related Issue #154
Added fields to add shipping name while setting facility postal address. Also displayed shipping name in the address and contact details card in facility details page.

Implemented: support to allow user to set shipping name for facility address (#154)

---

src/components/GroupActionsPopover.vue
src/router/index.ts
src/views/AddFacilityAddress.vue
src/views/AddFacilityConfig.vue
src/views/CreateFacility.vue
src/views/FacilityDetails.vue

#222 
After navigating to the facility details page, when the user clicks on the back button, the find-facilities page should open. Also, fix this issue in other components where navigating back to the find-facilities page is not working.

Fixed: Able to redirect to the find facilities page(#222)

---

src/components/FacilityAddressModal.vue
src/views/AddFacilityAddress.vue

Related Issue #154
- Improved code to not display contact number prefix when no countryCode is selected.
- Made zipCode mandatory while adding and updating contact number.

Improved: made zipCode mandatory, hide contact number prefix when no countryCode is selected (#154)

---

src/components/FacilityAddressModal.vue
src/views/AddFacilityAddress.vue

Related Issue #162
Fixed the position of the zipcode label to be shown in the facility address creation and updation.
Before 
After

Fixed: zipcode label not showing in facility address modal (#162)

---

src/store/modules/facility/actions.ts

#241 
When scrolling the page where infinite scroll is used , the previously loaded data should not be cleared if a corresponding api fails.

Improved: empty state will not show on api fail(#241)

---

src/views/FindFacilities.vue
src/views/FindGroups.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: Infinite scroll with searchbar and loading bug(#289)

---

src/views/FacilityDetails.vue

#247 
- Removed the `v-if` check on the `ion-avatar` tag for the `Image` component.

Fixed: inconsistency in the UI in retail store logins card(#247)

---

src/components/AddProductStoreToGroupModal.vue
src/views/FindGroups.vue

#253 
-  When no product stores are selected, the chip within a faciliy group should display "0".
- Added `bottom-padding` in the `ion-content` for preventing the overlapping of `ion-fab-button`.
- Added loader while opening the modal to prevent the delay tick marks on the Product stores.

Fixed: Interaction Issues in Product Stores Modal(#253)

---

src/store/modules/facility/actions.ts

#271
Added check to use cached facility info only if facility additional information is available in cache state.

Improved: logic for using cached facility info in case facility additional information is available (#271)

---

src/store/modules/facility/actions.ts

#250
- Filtering by date only if facility group filter is applied while fetching facilities.
- Removed facility filtering on primaryFacilityGroupId.

Improved: removed primaryFacilityGroupId filter while fetching facilities, and added filterByDate only if facilityGroup filter is applied(#250)

---

src/theme/variables.css

#165
Added align items start css to the find class.
Before
After

Improved: aligned items to start in the find groups page (#165)

---

src/components/CreateVirtualFacilityModal.vue

#185
Displaying error message from server dynamically in case of parking creation api fails due to duplicate facilityId.

Improved: error handling while parking creation to show error message from server (#185)

---

src/store/modules/facility/actions.ts

Improved: Fixed code logic to prevent facilities list from becoming empty if the infinite scroll call fails(#282)

---

src/views/FindFacilities.vue
src/views/FindGroups.vue
src/views/Parking.vue

#289 
changed padding for main in find facility , find group and parking , variable css was overriding , defined for each page specifically , verified changes for different resolutions

Fixed: Card content is hidden behind the tab-bar (#289)

---

src/components/FacilityGroupDescriptionModal.vue
src/locales/en.json
src/views/CreateFacilityGroup.vue
src/views/FindGroups.vue
src/views/ManageFacilities.vue
src/views/Parking.vue

#
Fixed following issues - 
#1 - It's observed that an alert doesn't trigger, and the sequence gets saved when the user tries to go back after saving the sequence for the first time. Hence, reopening this ticket.
#2 - Facilities count is not getting updated when user creates new group, unlink the facility after linking and then save the changes.
#3 - Facility counts disappear from group cards after navigating between the 'Facility Groups' and 'Parent Groups Associations' tabs without saving changes to facility sequencing.
#4 - Unnecessary scrollbar is present in 'Parent Group Association' tab. On scrolling the page, it gets disappear.
#5 - API gets fail and description(long) is not getting updated. Toast message is also not correct in this case. Also description is not getting saved in …

Fixed: Miscellaneous issues in new facility group UI (#293)

---

src/components/OrderLimitPopover.vue

https://github.com/hotwax/available-to-promise/pull/362
Prefilling the alert input in the custom maxOrder limit popover with the existing fulfillment order limit.

Improved: pre-filling the custom order limit alert input with the current maxorder limit

---

src/views/CreateFacilityGroup.vue
src/views/FindGroups.vue
src/views/ManageFacilities.vue

#305 #306 #307 #308
#
1) Fixed: Corrected logic to avoid saving duplicate members when adding/removing multiple times from the manage facilities page.
2) Fixed: Reset query string on reopening the manage facilities page after saving.
3) Fixed: Parent Group Association Not Opening After Tab Switching·
4) Fixed: Pressing Enter or Shift+Enter in any input field during facility group creation leads to the next step for creating a facility group.

Fixed: miscellaneous fixes related to new facility group UI. 

---

src/components/ProductStorePopover.vue
src/locales/en.json
src/views/FacilityDetails.vue

#304 
- Added a toast when we cannot set the product store as primary due to a missing Shopify shop.
- Also update the locale file with the toast text message.
- Also added a check to avoid adding the ion-badge to product stores without a Shopify shop ID.

Improved: Added a toast when we cannot set the product store as primary due to a missing Shopify shop(#304)

---

src/views/Parking.vue

#291
Restricted the parking card height to the card content.
Before
After

Improved: restricted the card height to the content in parkings page (#291)

---

src/views/AddFacilityConfig.vue
src/views/FacilityDetails.vue

#309 
- Earlier, all calls were made at the same time (in parallel), which could have caused concurrency issues and the error `Transaction is marked for rollback.`
- Now, the calls are made one after another (sequentially), which helps avoid these concurrency problems.

Improved: changed logic of api call for adding mutilple productStores to a facility(#309)

---

src/components/FacilityGeoPointModal.vue
src/components/GeoPointPopover.vue
src/views/AddFacilityAddress.vue
src/views/FacilityDetails.vue

#320 
- Added logic to fetch the latitude and longitude for zip codes starting with 0.
- Added functionality to regenerate the popover when the user edits latitude and longitude from the modal, or when a facility address is added.
- Also added a check on the facility details page to compare the correct zip code based on latitude and longitude.

Fixed: Zip codes starting with 0 now generate the latitude and longitude correctly(#320)

---

src/components/AddFacilityGroupModal.vue

#258 
- Previously, the group type in the modal was shown as 'null' for facility groups not linked to any specific type.
- This has been changed to 'Others' in the modal for groups with a null facilityGroupTypeId.

Fixed: Modal will display `Other` as group type for unlinked facility groups(#258)

---

src/views/FacilityDetails.vue

#323
The issue was resolved by displaying the productStoreId as a fallback when the store name is missing, ensuring no empty list items appear.

Fixed facility store name (#323)

---

src/services/FacilityService.ts

#322 
- Added logic to fetch the linked facilities for the linked facility group if the linked facility count exceeds 250 (viewSize).
- A `do-while` loop has been added to fetch the facilities until the total count is reached.

Improved: Added logic to fetch the facilities for the linked facility group if it exceeds the view size (#322)

---

src/components/ProductStorePopover.vue

#304 
- Fixed the issue where the product store option popover was not closing when setting the store as primary.
- Corrected the primary store tag display to appear as expected when relinking a store that was previously set as the primary before being unlinked.

Improved: Fixed popover not closing and corrected the primary store tag display issue(#304)

---

src/components/CreateVirtualFacilityModal.vue
src/views/CreateFacility.vue
src/views/CreateFacilityGroup.vue

#265 
- Added a check to prevent auto-population of the facilityId and facilityGroupId after manual edits, as they were previously auto-populated after every facilityName update.

Improved: Added a flag to prevent auto-population of the facility ID after it has been manually edited(#265)

---

src/components/AddFacilityGroupModal.vue
src/locales/en.json

#318
#
Improved: Added empty state in Add group modal  when linking a facility group to a facility.(#318)

Improved: Added empty state in Add group modal  when linking a facility group to a facility.(#318)

---

src/services/FacilityService.ts
src/views/FacilityDetails.vue
src/views/ManageFacilities.vue

Implemented: Bulk API calls to add facility to group and to update facility to group on Manage Facilities page.(#339)

---

src/components/SellOnlineGroupPopover.vue
src/locales/en.json
src/store/modules/facility/actions.ts
src/views/FindFacilities.vue

#256
- Added `Sell Online` popover on the facility list pages, which appears when clicking on the `Sell Online` chip.  
- In the popover, users can associate the inventory channel group with the facility using a checkbox.

Implemented: Added a Sell Online popover on the find facilities page(#256)

---

src/components/SellOnlineGroupPopover.vue
src/utils/index.ts
src/views/FindFacilities.vue

#256 
- Previously, in the case of a single facility group, the chip was still opening the popover, which was not the expected behavior.  
- So, handled the case by adding `updateFacilityGroup` as a utility function that works for both scenarios: selecting a single facility group via the chip and selecting multiple groups via the popover checkboxes.  
- Adding this utility function reduces redundant code.

Improved: Handled single Sell Online facility group case and added a common util function (#256)

---

src/components/AddOperatingHoursModal.vue

#333
- Fixed Saved facility calendar is not expanding on clicking the calendar item (not the down arrow) a second time.
https://jam.dev/c/f4cdf8c5-d732-406a-9016-e8171ec088f7

Fixed : Saved facility calendar is not expanding (#333)
