hotwax/facilities

.firebaserc
firebase.json

Implemented: configuration files for firebase

---

src/services/FacilityService.ts
src/store/modules/facility/actions.ts
src/views/FacilityDetails.vue

Closes #
- Defined separate action for fetching additional information for facilities
- Fetched latest additional information after performing an action

Improved: logic to fetch latest additional information for facility after performing an action on details page

---

src/components/AddLocationModal.vue
src/components/FacilityAddressModal.vue
src/components/FacilityGeoPointModal.vue

Closes #
Improved code for adding floating labels for inputs in modals.

Improved: code to add floating input labels in modals

---

src/views/CreateFacility.vue

Improved: removed clear input option for better keyboard navigation

---

src/store/modules/facility/actions.ts
src/views/FindFacilities.vue

Fixed: flickering on sell online status and capacity change by updating the state instead of refetching  the facilities

---

src/services/FacilityService.ts
src/store/modules/facility/actions.ts
src/views/Parking.vue

Closes #
Improved: Added pagination and improved logic.

Improved: Added pagination and improved logic.

---

src/components/ProductStorePopover.vue
src/components/VirtualFacilityActionsPopover.vue
src/views/AddFacilityConfig.vue

Fixed: incorrect fieldList parameter sent in FacilityGroup entity

---

src/components/AddOperatingHoursModal.vue
src/views/FacilityDetails.vue

Closes #71
Improved code to display calendarID in case when calendar description is null.

Improved: code to display calendarId if description not given (#71)

---

src/views/CreateFacility.vue

Closes #77
Improved code to by default select RETAIL STORE and WAREHOUSE in the select option.

Improved: code for making retail store and warehouse be selected by default(#77)

---

src/views/FacilityDetails.vue

Closes #
Improved: Displayed loader while changing fulfillment settings from facility detail page.

Improved: Displayed loader while changing fulfillment settings from facility detail page.

---

src/components/AddOperatingHoursModal.vue
src/locales/en.json
src/views/FacilityDetails.vue

Closes #90
- Improved code to display closed if no time is alloted for a day.
- Fixed getTime format for start Time to get time in 12 hrs format.

Improved: code to display closed if not day time given and start time in 12 hrs format (#90)

---

src/components/FacilityAddressModal.vue
src/views/FacilityDetails.vue

Closes #89
Improved code to automatically check and displays if zipCode matches for given latitude and longitude, on updation of Zip code from the address modal.

Improved: code to automatically check if zipcode matches lat-long on zipcode updation from address modal (#89)

---

src/views/FacilityDetails.vue

Fixed: UI issue regarding zipCode changing the state from danger to normal on initial load

---

src/components/CreateFacilityGroupModal.vue
src/components/CreateVirtualFacilityModal.vue
src/components/FacilityGroupActionsPopover.vue
src/utils/index.ts
src/views/CreateFacility.vue

Fixed: create and delete not working properly implemented util function to generate internal ID

---

src/services/FacilityService.ts

Fixed: facility count not visible if one of the fetched responses fail

---

src/views/CreateFacility.vue

Fixed: create flow to not call create location api untill facility is not created

---

src/components/CustomScheduleModal.vue

Fixed: logic to not remove associated calendar untill app level checks are not completed(#101)

---

src/store/modules/facility/actions.ts

Closes #110
Fixed issue: address, geopoint and product store fetching error on order limit updation

Fixed: address, geopoint and product store fetching error on order limit updation(#110)

---

src/views/FacilityDetails.vue

Fixed: warning for missing ion-avatar component import on details page

---

src/services/UserService.ts
src/store/modules/facility/actions.ts
src/views/FacilityDetails.vue

Closes #
Implemented: Displayed logo image for the facility login user.

Implemented: Displayed logo image for the facility login user.

---

src/views/FacilityDetails.vue

Closes #133 
The changes for checking null value for externalId were removed while resolving conflicts in this PR https://github.com/hotwax/facilities/pull/108
https://github.com/hotwax/facilities/pull/108/files#diff-a2d088e273ebf6b970cc5096d9c2bd0dc9a006e2f4ba943d083f9ccf2ba401f3L337

Reverted: changes for null check for externalId those were removed in conflict resolution(#133)

---

src/store/modules/facility/actions.ts

Closes #115 
Fixed: facility logins fetching logic (#115).

Fixed: facility logins fetching logic (#115).

---

src/locales/en.json
src/views/FacilityDetails.vue

Closes #144 
Improved: toast message while removing party from facility (#144).

Improved: toast message while removing party from facility (#144).

---

src/locales/en.json
src/views/FacilityDetails.vue

Closes #
Improved: toast message while removing party from facility (144).

Improved: toast message while removing party from facility (144).

---

src/components/FacilityShopifyMappingModal.vue

Closes #150
Improved code to auto select shopify config when adding external mapping.

Improved: code for auto select first shopify config when adding mapping(#150)

---

package-lock.json
package.json

Closes #
Updated: app version for the minor release (1.1.0).

Updated: app version for the minor release (1.1.0).

---

src/components/FacilityAddressModal.vue
src/store/modules/util/actions.ts
src/views/AddFacilityAddress.vue

Closes #
Improved code to show english translation of foreign states in facilites address modal.

Improved: code to show english translation of foreign states in facility address modal

---

src/store/modules/user/actions.ts

Added: Support to Remove Duplicate Permission Ids passed in the API request.

---

src/components/CreateFacilityGroupModal.vue
src/locales/en.json
src/store/modules/facility/actions.ts
src/views/FacilityDetails.vue

Closes #167
Implemented logic to give create inventory channel group support in sell inventory card in facilities detail page.

Implemented: create inventory group support in sell inventory card (#167)

---

package-lock.json
package.json

Updated: app version for minor release(1.2.0)

---

src/views/FacilityDetails.vue

Closes #192
- Fixed truncation issue in identification card card.
- Implemented copy functionality for the identification in the external mapping card.

Implemented: copy utility for identification in external mapping card and fixed truncation (#192)

---

package-lock.json
package.json

Updated: app version for minor release (v1.3.0)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.3.1)

---

src/components/AddFacilityToGroupModal.vue
src/components/AddProductStoreToGroupModal.vue
src/locales/en.json
src/services/FacilityService.ts
src/store/modules/facility/actions.ts
src/views/FindGroups.vue

Closes #210
Added support to link / unlink product stores to facility group.

Implemented: logic to link group to product stores (#210)

---

src/views/FacilityDetails.vue
src/views/FindFacilities.vue

Closes #174 
Removed frontend link from shipify card under external mapping tab to simplify UI.

Removed frontend link from shopify card under external mapping tab to simplify UI (#174)

---

package-lock.json
package.json

Closes #
Updated: app version for minor release (1.4.0).

Updated: app version for minor release (1.4.0).

---

package-lock.json
package.json
src/main.ts
vue.config.js

https://github.com/hotwax/dxp-components/issues/280
-Removed i18n package from the app.\
- passed the localemessgaes to the dxp component 
- update the vue.config.js file

Removed: Dependencies on i18n and  passed locale to dxp-component(dxp/280)

---

package-lock.json
package.json

Related Issue https://github.com/hotwax/dxp-components/issues/275

Improved: version of dxp-components package to have support for the goToOms fix(dxp/275)

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v1.5.0)

---

src/views/AddFacilityAddress.vue
src/views/Settings.vue

Closes #
Fixed: Label alignment in the create facility address form. Also updated usage of dxp component as per new names. (#154)

Fixed: Label alignment in the create facility address form. Also updated usage of dxp component as per new names. (#154)

---

src/store/modules/facility/actions.ts

#235 
Fixed the issue of duplication of virtual facilities on the parking page in facilities application.

Fixed: the coming of duplicate virtual facilities on parking page (#235)

---

package-lock.json
package.json

Closes #
Updated: app version for minor release (v1.6.0).

Updated: app version for minor release (v1.6.0).

---

.gitignore

Improved: gitignore for adding firebase and history entries

---

package-lock.json
package.json

Improved: app version in package and lock file for patch release(v1.6.1)

---

src/store/modules/util/actions.ts

#239 
Increased the viewSize from 10 to 250 for both countries in DBIC and states from 100 to 250.

Updated: increase the viewSize of DBIC countries and states(#239)

---

src/main.ts

#162 
- Added a entry in `main` file to fix html tags not working in the translations.

Fixed: html tags not working in the translations (#162)

---

src/store/modules/facility/actions.ts

Related Issue #250
Improved the state updation for fetchFacilities action to update state in case of no record found.

Fixed: state not updating in case of no record for fetching facilities (#250)

---

src/store/modules/user/actions.ts
src/views/FindFacilities.vue

Related Issue #267
Added support for redirection to find facilities page along with productStore filter when redirecting from the company app.

Implemented: support for redirecting user to findFacilities page along with productStoreId coming in query (#267)

---

package-lock.json
package.json

Updated: app version for the minor release (v1.8.0)

---

package-lock.json
package.json

Updated: app version for the patch release(v1.8.1)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.8.2)

---

src/views/FindGroups.vue

#291 
Added a horizontal line between product store and facility and removed line from the last

Fixed: Added a horizontal line between product store and facility and removed line from the last (#291)

---

src/components/CustomMappingModal.vue
src/components/FacilityAddressModal.vue
src/components/FacilityExternalIdModal.vue
src/components/FacilityMappingModal.vue
src/components/FacilityMappingPopover.vue
src/components/FacilityShopifyMappingModal.vue
src/views/FacilityDetails.vue

#132 
Added id on inputs to be focused and used js to add focus on the input after modal is being presented.

Implemented: support to add focus on first input element inside mapping modals(#132)

---

src/views/ManageFacilities.vue
src/views/Parking.vue

#291
Improved the lines property in the parking card items for the consistency.
Before
After

Improved: code for adding consistency in the item bottom lines in parking cards (#291)

---

src/views/FindGroups.vue

#293 
#
Fixed: Cleared query string on tab change in order to get the correct data in parent group tab (#293).

Fixed: Cleared query string on tab change in order to get the correct data in parent group tab (#293).

---

package-lock.json
package.json

#
Updated: app version for patch release v1.9.3.

Updated: app version for patch release v1.9.3.

---

src/views/FacilityDetails.vue

Improved: case to display productStoreId when name for the productStore is missing(#323)

---

package-lock.json
package.json

Updated: app version for minor release v1.10.0

---

src/views/FindGroups.vue

#342
Improved the event handling for the association of facility group to parent

Fixed: click event to toggle association of facility group to parent not working on clicking on label (#342)

---

src/views/AddFacilityAddress.vue

#341 
#
Improved: Prevented non-numeric characters in the phone number field.(#341)

Improved: Prevented non-numeric characters in the phone number field.(#341)

---

src/components/AddFacilityGroupModal.vue
src/services/FacilityService.ts

#328 
- Added pagination for services fetching `facilityGroups` (fetches all facility groups irrespective of the facility) and `fetchFacilityGroupInformation` (fetches facility group information for the given `facilityId`).
- All related facility groups are visible in the `Groups` segment on the `Facility Details` page.  
- The `Fulfillment Settings` toggles, such as `Fulfillment Settings` and `Sell Inventory Online`, are working fine.  
- Linked groups to the facility are displayed correctly regardless of the count.  
- The `Add Group` modal shows all available groups, and you can add or remove facility groups using checkboxes, which now update correctly on both the modal and the details page.

Fixed: Inconsistency of facility groups on facility details page(#328)

---

package-lock.json
package.json

Updated: app version for minor release  v1.11.0

---

src/components/FacilityLoginActionPopover.vue

https://github.com/hotwax/users/issues/102

Improved: users app redirection url to pass the current path(users/102)

---

src/App.vue
src/locales/en.json
src/store/modules/user/actions.ts

Fixed: updated loader behavior to disable backdrop dismissal and changed default loading messages. (hotwax/dxp-components#321)

---

src/store/modules/facility/mutations.ts

Removed: duplicate mutation defination for postal address update

---

package-lock.json
package.json

Updated: app version for minor release v1.12.0

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v1.13.0)
